project_id = "znmtzjwwmuchkqwnkfmb"

[functions.chat-ai]
verify_jwt = false

[functions.serve-site]
verify_jwt = false

[functions.publish-site]
verify_jwt = false

[functions.track-visit]
verify_jwt = false
